application: mouthpiece
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: .*
  script: main.py
